# Generated by Django 4.1.6 on 2023-02-14 19:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="page",
            name="title",
            field=models.CharField(default="Untitled", max_length=100),
        ),
    ]
