# Generated by Django 4.1.6 on 2023-02-15 02:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("page", "0002_alter_page_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
